CREATE TABLE alocacao
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    horas_semana INT    NOT NULL,
    pessoa_id    BIGINT NOT NULL,
    projeto_id   BIGINT NOT NULL,
    perfil_id    BIGINT NOT NULL,
    CONSTRAINT pk_alocacao PRIMARY KEY (id)
);

CREATE TABLE contrato
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_inicio  date,
    data_fim     date,
    horas_semana INT              NOT NULL,
    salario_hora DOUBLE PRECISION NOT NULL,
    pessoa_id    BIGINT           NOT NULL,
    CONSTRAINT pk_contrato PRIMARY KEY (id)
);

CREATE TABLE perfil
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo VARCHAR(255),
    CONSTRAINT pk_perfil PRIMARY KEY (id)
);

CREATE TABLE pessoa
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(255),
    CONSTRAINT pk_pessoa PRIMARY KEY (id)
);

CREATE TABLE projeto
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR(255),
    data_inicio date,
    data_fim    date,
    descricao   VARCHAR(255),
    CONSTRAINT pk_projeto PRIMARY KEY (id)
);

ALTER TABLE alocacao
    ADD CONSTRAINT FK_ALOCACAO_ON_PERFIL FOREIGN KEY (perfil_id) REFERENCES perfil (id);

ALTER TABLE alocacao
    ADD CONSTRAINT FK_ALOCACAO_ON_PESSOA FOREIGN KEY (pessoa_id) REFERENCES pessoa (id);

ALTER TABLE alocacao
    ADD CONSTRAINT FK_ALOCACAO_ON_PROJETO FOREIGN KEY (projeto_id) REFERENCES projeto (id);

ALTER TABLE contrato
    ADD CONSTRAINT FK_CONTRATO_ON_PESSOA FOREIGN KEY (pessoa_id) REFERENCES pessoa (id);